### ISSUE TITLE
It seems that the compressed file is bigger than the original image.

### ISSUE THREAD

**Issue by t04dJ14n9** [ghallak/jpeg-python#11]
I have a png image with 423300 bytes.
After I ran
python ./encoder.py input.png output.jpg
The output.jpg file had 1565098 bytes.

**Comment by walteshen** [comment]
> I have a png image with 423300 bytes. After I ran python ./encoder.py input.png output.jpg The output.jpg file had 1565098 bytes.

This is because only Huffman encoding is performed in the source code, and Huffman decoding is not used on the decoding. When saving the file, the data without Huffman encoding is also saved.
